export const CoinFlipAbi = [
  {
     "inputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"constructor"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"player",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"betAmount",
           "type":"uint256"
        },
        {
           "indexed":false,
           "internalType":"bool",
           "name":"win",
           "type":"bool"
        }
     ],
     "name":"CoinFlipped",
     "type":"event"
  },
  {
     "inputs":[
        {
           "internalType":"uint8",
           "name":"guess",
           "type":"uint8"
        }
     ],
     "name":"flipCoin",
     "outputs":[
        
     ],
     "stateMutability":"payable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"owner",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"withdraw",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "stateMutability":"payable",
     "type":"receive"
  }
] as const;
