///@ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/xbox_controller_lp.glb -t -o src/components/Three/models/Controller.tsx 
Author: VioletBoom (https://sketchfab.com/violetboom)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xbox-controller-lp-1658ffe50e154dd8b830412a6f845b37
Title: Xbox Controller LP
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['25_surf0000_1_0_0_root_root_ground003_1']: THREE.Mesh
    ['25_surf0000_1_0_0_root_root_ground003_2']: THREE.Mesh
    ['25_surf0000_1_0_0_root_root_ground003_3']: THREE.Mesh
    ['25_surf0000_1_0_0_root_root_ground003_4']: THREE.Mesh
    ['25_surf0000_1_0_0_root_root_ground003_5']: THREE.Mesh
    ['25_surf0000_1_0_0_root_root_ground003_6']: THREE.Mesh
    ['25_surf0000_1_0_0_root_root_ground003_7']: THREE.Mesh
    ['25_surf0000_1_0_0_root_root_ground003_8']: THREE.Mesh
    ['25_surf0000_1_0_0_root_root_ground003_9']: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Controller(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/xbox_controller_lp.glb') as GLTFResult
  console.log({materials,nodes})
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.269, -0.098, 0.04]} scale={16.713}>
          <mesh geometry={nodes['25_surf0000_1_0_0_root_root_ground003_1'].geometry} material={materials['Material.002']} />
          <mesh geometry={nodes['25_surf0000_1_0_0_root_root_ground003_2'].geometry} material={materials['Material.004']} />
          <mesh geometry={nodes['25_surf0000_1_0_0_root_root_ground003_3'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['25_surf0000_1_0_0_root_root_ground003_4'].geometry} material={materials['Material.005']} />
          <mesh geometry={nodes['25_surf0000_1_0_0_root_root_ground003_5'].geometry} material={materials['Material.003']} />
          <mesh geometry={nodes['25_surf0000_1_0_0_root_root_ground003_6'].geometry} material={materials['Material.001']} />
          <mesh geometry={nodes['25_surf0000_1_0_0_root_root_ground003_7'].geometry} material={materials['Material.007']} />
          <mesh geometry={nodes['25_surf0000_1_0_0_root_root_ground003_8'].geometry} material={materials['Material.008']} />
          <mesh geometry={nodes['25_surf0000_1_0_0_root_root_ground003_9'].geometry} material={materials['Material.009']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/xbox_controller_lp.glb')
